apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tnoronha-repo
  description: sample tnoronha repo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/solution_architects
  lifecycle: experimental
